import { GoogleGenAI } from '@google/genai';

export class MedicalKnowledgeAgent {
  private ai: GoogleGenAI;

  constructor(apiKey: string) {
    this.ai = new GoogleGenAI({ apiKey });
  }

  /**
   * Purpose: Uses Gemini 2.5 to cross-reference predictions with clinical guidelines.
   * Acts as the Explainability Agent to generate natural language interpretations mimicking 
   * SHAP/Integrated Gradients feature importance from the PraOjas research.
   */
  async generateExplanation(patientData: any, prediction: any) {
    const prompt = `
      You are the PraOjas AI Medical Knowledge & Explainability Agent. 
      The prediction below was generated by our Self-Supervised Multimodal Transformer (which fuses Bio_ClinicalBERT notes and Temporal Transformer time-series data).
      
      Patient Data:
      Age/Gender: ${patientData.age} ${patientData.gender}
      Vitals: HR ${patientData.vitals.hr}, BP ${patientData.vitals.bp}, Temp ${patientData.vitals.temp}C, RR ${patientData.vitals.rr}, SpO2 ${patientData.vitals.spo2}%
      Labs: WBC ${patientData.labs.wbc}, Lactate ${patientData.labs.lactate} mmol/L, Creatinine ${patientData.labs.creatinine} mg/dL
      Clinical Notes: ${patientData.clinicalNotes}
      
      Model Prediction:
      Sepsis Probability: ${(prediction.sepsisProbability * 100).toFixed(1)}%
      Mortality Probability: ${(prediction.mortalityProbability * 100).toFixed(1)}%
      
      Task:
      1. Provide a concise clinical explanation mimicking SHAP/Integrated Gradients feature importance (e.g., "The primary drivers for this sepsis risk score are elevated Lactate and high Heart Rate").
      2. Provide a brief bulleted list of 3 recommended clinical actions based on standard Sepsis Bundles.
      Always include a disclaimer that this is decision support and not a final medical diagnosis. Keep it under 3 short paragraphs.
      
      Output ONLY a valid JSON object matching this structure:
      {
        "explanation": "Your natural language explanation...",
        "featureImportance": [
          { "feature": "Lactate", "importance": 0.85 },
          { "feature": "Heart Rate", "importance": 0.65 },
          { "feature": "Temperature", "importance": -0.2 }
        ]
      }
      Do not include any markdown such as \`\`\`json. The importance score should be a float between -1.0 and 1.0 (positive increases risk, negative decreases risk).
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          temperature: 0.2
        }
      });

      let responseText = response.text || "{}";
      responseText = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
      
      return JSON.parse(responseText);
    } catch (error) {
      console.error('Error generating explanation:', error);
      return {
        explanation: "Failed to generate clinical explanation.",
        featureImportance: []
      };
    }
  }

  async suggestSmartVitals(patientData: any) {
    const prompt = `
      You are an AI Medical Assistant simulating patient vitals progression.
      Based on the patient's current vitals, recent history, and status, suggest the likely current (next) reading of vitals.
      
      Patient Data:
      Age/Gender: ${patientData.age} ${patientData.gender}
      Current Vitals: HR ${patientData.vitals.hr}, BP ${patientData.vitals.bp}, Temp ${patientData.vitals.temp}C, RR ${patientData.vitals.rr}, SpO2 ${patientData.vitals.spo2}%
      Status: ${patientData.status}
      Sepsis Risk Trend: ${patientData.status === 'Critical' ? 'Increasing rapidly' : patientData.status === 'Warning' ? 'Slightly elevated' : 'Stable'}

      Suggest the next plausible reading for HR, BP, Temp, RR, and SpO2 reflecting realistic physiological progression.
      Output ONLY a valid JSON object matching this structure:
      {
        "hr": 85,
        "bp": "120/80",
        "temp": 37.2,
        "rr": 16,
        "spo2": 98
      }
      Do not include any markdown such as \`\`\`json.
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          temperature: 0.3
        }
      });

      let responseText = response.text || "{}";
      responseText = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
      
      return JSON.parse(responseText);
    } catch (error) {
      console.error('Error suggesting smart vitals:', error);
      return {
        hr: patientData.vitals.hr,
        bp: patientData.vitals.bp,
        temp: patientData.vitals.temp,
        rr: patientData.vitals.rr,
        spo2: patientData.vitals.spo2
      };
    }
  }
}
